import test from 'node:test';import assert from 'node:assert/strict';import ganache from 'ganache';import solc from 'solc';import {BrowserProvider,ContractFactory,ZeroHash,AbiCoder,keccak256} from 'ethers';import {artifact,catalog,rulesHash,manifest} from '../scripts/shared.mjs';
const roll=(word,scope,bound)=>BigInt(keccak256(AbiCoder.defaultAbiCoder().encode(['uint256','uint256','bytes32'],[word,scope,rulesHash])))%BigInt(bound);
test('v4 rounds: immutable quotas, tickets, VRF, FIFO, ten-block spacing and transfer',async t=>{
 const rpc=ganache.provider({chain:{chainId:1337},logging:{quiet:true}}),p=new BrowserProvider(rpc,undefined,{cacheTimeout:-1});p.pollingInterval=10;
 try{const a=await p.getSigner(0),b=await p.getSigner(1),c=await p.getSigner(2);const deploy=async(name,args=[])=>{let art=artifact(name),n=await new ContractFactory(art.abi,art.bytecode,a).deploy(...args);await n.waitForDeployment();return n;};
 const v=await deploy('MockVRF'),n=await deploy('Bnbfish',[await a.getAddress(),await v.getAddress(),ZeroHash,1,3,rulesHash,'ipfs://example/',catalog]);
 const mine=async target=>{while(BigInt(await rpc.request({method:'eth_blockNumber',params:[]}))<target)await rpc.request({method:'evm_mine',params:[]});};
 const cast=async who=>{await(await n.connect(who).cast(0)).wait();return n.pendingRequest(await who.getAddress());};
 await t.test('hard total, all species quotas and no privileged mint/upgrade/setter',async()=>{let sum=0n;for(const s of catalog){const cap=await n.speciesCaps(s.id);assert.equal(cap,BigInt(manifest.species.find(x=>x.id===s.id).maxSupply));sum+=cap;}assert.equal(sum,2000000n);assert.equal(await n.ROUND_BLOCKS(),10n);assert.equal(await n.EMPTY_BPS(),2000n);for(const f of ['mint','configure','upgradeTo','setSpecies','setTierCaps','burn'])assert.equal(n.interface.hasFunction(f),false);await assert.rejects(()=>cast(b));await assert.rejects(()=>n.connect(b).setPaused(false));await(await n.setPaused(false)).wait();await assert.rejects(()=>n.connect(b).cast(0,{value:1}));});
 const id1=await cast(b),id2=await cast(b),id3=await cast(c),r1=await n.ticketRound(id1);
 await t.test('repeated tickets are distinct and round cannot request entropy before close',async()=>{assert.equal(await n.ticketRound(id3),r1);assert.equal(await n.playerTicketCount(await b.getAddress()),2n);assert.notEqual(id1,id2);await assert.rejects(()=>n.requestRound(r1));await assert.rejects(()=>n.rawFulfillRandomWords(1,[1]));});
 await mine(await n.roundEnd(r1));await(await n.requestRound(r1)).wait();const vr1=(await n.rounds(r1)).requestId;
 let w1=1n;while([id1,id2,id3].some(id=>roll(w1,100n+id*2n,10000)<2000n))w1++;
 const id4=await cast(b),r2=await n.ticketRound(id4);await mine(await n.roundEnd(r2));await(await n.requestRound(r2)).wait();let w2=1n;while(roll(w2,100n+id4*2n,10000)<2000n)w2++;
 await t.test('out-of-order callbacks cannot jump FIFO; repeat request and unauthorized entropy rejected',async()=>{await assert.rejects(()=>n.requestRound(r1));await(await v.fulfill((await n.rounds(r2)).requestId,w2,{gasLimit:1700000})).wait();assert.equal((await n.rounds(r2)).state,2n);assert.equal(await n.totalSupply(),0n);await assert.rejects(()=>n.settle(id4));});
 await t.test('VRF automatically chooses one among nonempty tickets; losers cannot mint',async()=>{await(await v.fulfill(vr1,w1,{gasLimit:1700000})).wait();const r=await n.rounds(r1);assert.equal(r.state,3n);assert.equal(r.eligible,3n);let expected=0n,eligible=0n;for(const id of [id1,id2,id3]){eligible++;if(roll(w1,101n+id*2n,eligible)===0n)expected=id;}assert.equal(r.winner,expected);assert.equal(await n.totalSupply(),1n);assert.equal(await n.ownerOf(r.tokenId),(await n.casts(expected)).player);for(const id of [id1,id2,id3])assert.equal((await n.outcome(id))[1],id===expected);await(await v.fulfill(vr1,0,{gasLimit:1700000})).wait();assert.equal((await n.rounds(r1)).winner,expected);});
 await t.test('delayed ready rounds cannot produce another NFT within ten blocks',async()=>{const firstBlock=await n.lastMintBlock();await(await n.processQueue(20)).wait();assert.equal(await n.totalSupply(),1n);await mine(firstBlock+9n);const receipt=await(await n.processQueue(20)).wait();assert.equal(await n.totalSupply(),2n);assert.ok(BigInt(receipt.blockNumber)-firstBlock>=10n);});
 await t.test('ERC721 transfer cannot alter supply or fish metadata',async()=>{const owner=await n.ownerOf(1),who=owner.toLowerCase()===(await b.getAddress()).toLowerCase()?b:c,recipient=await a.getAddress(),before=await n.fish(1);await(await n.connect(who)['safeTransferFrom(address,address,uint256)'](owner,recipient,1)).wait();assert.equal(await n.ownerOf(1),recipient);assert.deepEqual(Array.from(await n.fish(1)),Array.from(before));assert.equal(await n.totalSupply(),2n);});
 const id5=await cast(b),r3=await n.ticketRound(id5);await mine(await n.roundEnd(r3));await(await n.requestRound(r3)).wait();let empty=1n;while(roll(empty,100n+id5*2n,10000)>=2000n)empty++;
 await t.test('all-empty round mints nothing; paused recovery works; restart cannot reset epoch',async()=>{const epoch=await n.startBlock();await(await n.setPaused(true)).wait();await(await v.fulfill((await n.rounds(r3)).requestId,empty,{gasLimit:200000})).wait();assert.equal((await n.rounds(r3)).state,2n);await(await n.connect(c).processQueue(20)).wait();assert.equal((await n.rounds(r3)).state,3n);assert.equal((await n.outcome(id5))[1],false);assert.equal(await n.totalSupply(),2n);await(await n.setPaused(false)).wait();assert.equal(await n.startBlock(),epoch);await assert.rejects(()=>n.processQueue(21));});
 await t.test('large same-round entry uses bounded batches; batch sizes do not change winner',async()=>{const src='pragma solidity ^0.8.24; interface I {function cast(uint8) external payable returns(uint256);} contract Many { function enter(address n,uint count) external {for(uint i;i<count;i++)I(n).cast(0);} }';const out=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources:{'Many.sol':{content:src}},settings:{evmVersion:'paris',outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}})));const art=out.contracts['Many.sol'].Many;const many=await new ContractFactory(art.abi,'0x'+art.evm.bytecode.object,a).deploy();await many.waitForDeployment();await(await many.enter(await n.getAddress(),45,{gasLimit:12000000})).wait();const id=await n.issuedCasts(),rid=await n.ticketRound(id);assert.equal((await n.rounds(rid)).count,45n);await mine(await n.roundEnd(rid));await(await n.requestRound(rid)).wait();await(await v.fulfill((await n.rounds(rid)).requestId,123,{gasLimit:200000})).wait();const snap=await rpc.request({method:'evm_snapshot',params:[]});while((await n.rounds(rid)).state!==3n)await(await n.processQueue(20,{gasLimit:1600000})).wait();const winner=(await n.rounds(rid)).winner;await rpc.request({method:'evm_revert',params:[snap]});while((await n.rounds(rid)).state!==3n)await(await n.processQueue(7,{gasLimit:1600000})).wait();assert.equal((await n.rounds(rid)).winner,winner);assert.equal(await n.totalSupply(),3n);});
 }finally{await rpc.disconnect();}
});
