import test from 'node:test';import assert from 'node:assert/strict';import {createGlobalCatches} from '../service/global-catches.mjs';
function setup(){let time=100000,height=103,branch='a',broken=false;let fish=[{speciesId:1,player:'0x'+'1'.repeat(40)}];let fishReads=0,countReads=0;const tags=[];
 const provider={getNetwork:async()=>({chainId:56}),send:async()=>{if(broken)throw Error('offline');return '0x'+height.toString(16);},getBlock:async n=>({hash:branch+n})};
 const contract={rulesHash:async()=> 'rules',totalSupply:async o=>{tags.push(o.blockTag);return BigInt(fish.length);},speciesMinted:async id=>{countReads++;return BigInt(fish.filter(f=>f.speciesId===id).length);},fish:async(id,o)=>{fishReads++;tags.push(o.blockTag);const f=fish[id-1];return {...f,requestId:BigInt(id),caughtAt:1000n,water:0n};},tickets:async id=>({...fish[Number(id)-1],tokenId:id,state:2})};
 const feed=createGlobalCatches({provider,contract,chainId:56,address:'0x'+'a'.repeat(40),rulesHash:'rules',speciesIds:[1,2],ttlMs:10,now:()=>time});
 return {feed,tags,get reads(){return {fishReads,countReads};},advance(){time+=20;height+=10;},add(){fish.push({speciesId:2,player:'0x'+'2'.repeat(40)});},reorg(){branch='b';fish[0]={speciesId:2,player:'0x'+'3'.repeat(40)};},fail(){broken=true;},empty(){fish=[];}};
}
test('global feed counts mints, shows original catcher and incrementally caches fixed-block reads',async()=>{const f=setup();const [a,b]=await Promise.all([f.feed.get(),f.feed.get()]);assert.equal(a,b);assert.equal(a.total,1);assert.equal(a.latest[0].player,'0x'+'1'.repeat(40));assert.ok(f.tags.every(n=>n===100));const calls={...f.reads};await f.feed.get();assert.deepEqual(f.reads,calls);f.advance();f.add();const next=await f.feed.get();assert.equal(next.total,2);assert.equal(next.speciesCount,2);assert.deepEqual(next.latest.map(f=>f.tokenId),['2','1']);assert.equal(f.reads.countReads,calls.countReads);});
test('same-supply reorg rebuilds species and catcher; outage retains explicitly stale data',async()=>{const f=setup();await f.feed.get();f.advance();f.reorg();const changed=await f.feed.get();assert.equal(changed.species[0].speciesId,2);assert.equal(changed.latest[0].player,'0x'+'3'.repeat(40));f.advance();f.fail();const stale=await f.feed.get();assert.equal(stale.stale,true);assert.equal(stale.total,1);assert.equal(stale.blockHash,changed.blockHash);});
test('zero supply is real empty data; initial network failure never reports zero',async()=>{const f=setup();f.empty();const data=await f.feed.get();assert.equal(data.total,0);assert.deepEqual(data.latest,[]);const down=setup();down.fail();await assert.rejects(down.feed.get());});
