import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import solc from 'solc';import ganache from 'ganache';import {BrowserProvider,ContractFactory,Wallet,ZeroHash,AbiCoder,keccak256} from 'ethers';import {artifact,catalog,rulesHash} from '../scripts/shared.mjs';
// Test-only state seeding reaches the two-millionth mint without sending two million transactions.
// The production contract has no seeding endpoint and retains its original constants and selection code.
test('last NFT cannot oversubscribe, sold-out species are excluded, pending casts drain safely',async()=>{
 const harness='pragma solidity ^0.8.24; import "Bnbfish.sol"; contract SupplyHarness is Bnbfish { constructor(address a,address v,address p,Species[] memory c,bytes32 h) Bnbfish(a,v,bytes32(0),1,3,h,"ipfs://test/",c) {} function seedLast(uint16 id,uint16[] calldata ids) external onlyOwner { for(uint256 i;i<ids.length;i++) speciesMinted[ids[i]]=speciesCaps[ids[i]]; for(uint256 i;i<5;i++)tierMinted[i]=tierCaps[i];speciesMinted[id]--;tierMinted[species[id].tier]--;for(uint256 w;w<3;w++)for(uint256 t;t<5;t++)remainingPool[w*5+t]=0;for(uint8 w;w<3;w++)if(species[id].waters&(uint8(1)<<w)!=0)remainingPool[uint256(w)*5+species[id].tier]=1;nextTokenId=MAX_SUPPLY; }}';
 const out=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources:{'Bnbfish.sol':{content:fs.readFileSync('contracts/Bnbfish.sol','utf8')},'SupplyHarness.sol':{content:harness}},settings:{optimizer:{enabled:true,runs:200},viaIR:true,evmVersion:'paris',outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}}),{import:p=>({contents:fs.readFileSync('node_modules/'+p,'utf8')})}));assert.ok(!out.errors?.some(e=>e.severity==='error'),JSON.stringify(out.errors));
 const rpc=ganache.provider({chain:{chainId:1337},logging:{quiet:true}}),provider=new BrowserProvider(rpc);provider.pollingInterval=10;
 try{const admin=await provider.getSigner(0),players=[await provider.getSigner(2),await provider.getSigner(3)],authority=new Wallet(Object.values(rpc.getInitialAccounts())[1].secretKey);const a=artifact('MockVRF'),vrf=await new ContractFactory(a.abi,a.bytecode,admin).deploy();await vrf.waitForDeployment();const h=out.contracts['SupplyHarness.sol'].SupplyHarness,nft=await new ContractFactory(h.abi,'0x'+h.evm.bytecode.object,admin).deploy(await admin.getAddress(),await vrf.getAddress(),authority.address,catalog,rulesHash);await nft.waitForDeployment();await(await nft.setPaused(false)).wait();
 const last=catalog.find(s=>(s.waters&1)!==0);await(await nft.seedLast(last.id,catalog.map(s=>s.id))).wait();assert.equal(await nft.waterRemaining(0),1n);
 const ids=[];for(const player of players){await(await nft.connect(player).cast(0)).wait();ids.push(await nft.pendingRequest(await player.getAddress()));}
 const rid=await nft.ticketRound(ids[0]);while(BigInt(await rpc.request({method:'eth_blockNumber',params:[]}))<await nft.roundEnd(rid))await rpc.request({method:'evm_mine',params:[]});await(await nft.requestRound(rid)).wait();
 let word=1n;const eligible=id=>BigInt(keccak256(AbiCoder.defaultAbiCoder().encode(['uint256','uint256','bytes32'],[word,100n+id*2n,rulesHash])))%10000n>=2000n;while(!ids.every(eligible))word++;
 await(await vrf.fulfill((await nft.rounds(rid)).requestId,word,{gasLimit:1700000})).wait();assert.equal(await nft.nextTokenId(),2000001n);assert.equal(await nft.speciesMinted(last.id),await nft.speciesCaps(last.id));assert.equal(await nft.waterRemaining(0),0n);assert.equal((await nft.fish(2000000)).speciesId,BigInt(last.id));assert.equal((await nft.rounds(rid)).state,3n);assert.equal(await nft.totalSupply(),1n);
 await(await nft.processQueue(20)).wait();assert.equal(await nft.nextTokenId(),2000001n);await assert.rejects(()=>nft.connect(players[0]).cast(0));for(let t=0;t<5;t++)assert.equal(await nft.tierMinted(t),await nft.tierCaps(t));
 }finally{await rpc.disconnect();}
});
