import express from 'express';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {JsonRpcProvider,Contract,getAddress} from 'ethers';import {artifact,rulesHash} from '../scripts/shared.mjs';
import {createGlobalCatches} from './global-catches.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const cfg=JSON.parse(fs.readFileSync(path.resolve(root,process.env.Bnbfish_CONFIG||'config/production.json'),'utf8'));
if(![56,1337].includes(cfg.chainId)||cfg.chainId===1337&&!cfg.local)throw Error('Unsupported deployment environment');
const provider=new JsonRpcProvider(process.env.BNB_RPC_URL||cfg.rpcUrl,cfg.chainId,{staticNetwork:false});
function selection(){return cfg;}
function bundle(c){if(c.protocol==='claim200-reserved-v2')return {abi:JSON.parse(fs.readFileSync(path.join(root,'artifacts/claim200/BnbfishClaim200.json'),'utf8')).abi,hash:JSON.parse(fs.readFileSync(path.join(root,'artifacts/claim200/rules.json'),'utf8')).hash};const blockhash=c.protocol==='blockhash-continuous-v1';return {abi:blockhash?JSON.parse(fs.readFileSync(path.join(root,'artifacts/blockhash/BnbfishBlockhash.json'),'utf8')).abi:artifact('Bnbfish').abi,hash:blockhash?JSON.parse(fs.readFileSync(path.join(root,'artifacts/blockhash/rules.json'),'utf8')).hash:rulesHash};}
const nft=!!cfg.contract;
const app=express();app.disable('x-powered-by');app.use(express.json({limit:'8kb'}));
// Some public BNB endpoints return incomplete JSON-RPC batches; feed reads use individual requests.
const feedProvider=new JsonRpcProvider(process.env.BNB_FEED_RPC_URL||(cfg.chainId===56?'https://bsc-rpc.publicnode.com':cfg.rpcUrl),cfg.chainId,{staticNetwork:false,batchMaxCount:1});
const globalFeed=cfg.contract&&['blockhash-continuous-v1','claim200-reserved-v2'].includes(cfg.protocol)?createGlobalCatches({provider:feedProvider,contract:new Contract(getAddress(cfg.contract),bundle(cfg).abi,feedProvider),chainId:cfg.chainId,address:getAddress(cfg.contract),rulesHash:bundle(cfg).hash,claim200:cfg.protocol==='claim200-reserved-v2',speciesIds:JSON.parse(fs.readFileSync(path.join(root,cfg.protocol==='claim200-reserved-v2'?'artifacts/claim200/rules.json':'artifacts/blockhash/rules.json'),'utf8')).rules.catalog.map(s=>s.id)}):null;
app.use((req,res,next)=>{res.set('X-Content-Type-Options','nosniff');res.set('Referrer-Policy','no-referrer');res.set('Cache-Control',req.path.startsWith('/api/')?'no-store':'public, max-age=60');next();});
app.get('/api/config',(req,res)=>{const c=selection(req),b=bundle(c);res.json({chainId:c.chainId,name:c.name,explorer:c.explorer,contract:c.contract,deploymentBlock:c.deploymentBlock,baitFeeBnb:c.baitFeeBnb,protocolFeeWei:c.protocolFeeWei,feeRecipient:c.feeRecipient,archived:!!c.archived,rulesHash:b.hash,protocol:c.protocol||'vrf-v4',legacy:false,local:!!c.local,releaseStage:c.local?'local-testing':c.releaseStage||'unspecified',releaseLabel:c.releaseLabel||'',permitEnabled:false,entryMode:'wallet-direct',rpcUrl:c.rpcUrl});});
app.get('/api/contract-abi',(req,res)=>res.json({abi:bundle(selection(req)).abi}));
app.get('/api/status',async(req,res)=>{try{const c=selection(req),b=bundle(c);const [network,height]=await Promise.all([provider.getNetwork(),provider.getBlockNumber()]);if(Number(network.chainId)!==c.chainId)throw Error('RPC_CHAIN_MISMATCH');if(!c.contract)return res.json({height,ready:false,reason:'合约尚未部署'});const n=new Contract(getAddress(c.contract),b.abi,provider);if(await n.rulesHash()!==b.hash)throw Error('RULES_MISMATCH');const [paused,fee]=await Promise.all([n.paused(),c.protocol==='claim200-reserved-v2'?n.protocolFee():n.baitFee()]);const archived=!!c.archived;res.json({height,ready:!paused&&!archived,fee:fee.toString(),reason:archived?'旧版仅保留记录与 NFT 转账':paused?'合约暂停':''});}catch(e){res.status(503).json({ready:false,error:e.shortMessage||e.message});}});
app.get('/api/automation',(req,res)=>{try{const c=selection(req);const file=process.env.KEEPER_STATUS_FILE||(c.protocol==='claim200-reserved-v2'?'/var/lib/bnbfish-claim200-keeper/status.json':c.protocol==='blockhash-continuous-v1'?'/var/lib/bnbfish-blockhash-keeper/status.json':'/var/lib/bnbfish-keeper/status.json'),s=JSON.parse(fs.readFileSync(file,'utf8')),fresh=Date.now()-s.updatedAt<45000,matching=!['claim200-reserved-v2','blockhash-continuous-v1'].includes(c.protocol)||s.contract?.toLowerCase()===c.contract?.toLowerCase();res.json({contract:c.contract,address:s.address,ready:fresh&&matching&&s.ready,code:!matching?'not-configured':fresh?s.code:'offline',updatedAt:s.updatedAt});}catch{res.json({ready:false,code:'not-configured'});}});
app.get('/api/global-catches',async(req,res)=>{if(!globalFeed)return res.status(503).json({error:'FEED_NOT_CONFIGURED'});try{res.json(await globalFeed.get());}catch(e){console.warn('global-catches unavailable',e.code||'READ_FAILED',e.shortMessage||(/^[A-Z_]+$/.test(e.message)?e.message:'RPC read failed'));res.status(503).json({error:'FEED_UNAVAILABLE'});}});
app.use(express.static(path.join(root,'web'),{dotfiles:'deny'}));
app.use((err,req,res,next)=>res.status(400).json({error:'INVALID_REQUEST'}));
const port=Number(process.env.PORT||4187);app.listen(port,process.env.HOST||'127.0.0.1',()=>console.log(`Bnbfish BNB web: http://127.0.0.1:${port}; chain ${cfg.chainId}; ${nft?'configured':'NOT DEPLOYED'}`));
