import {clearRetiredCollections} from './collection-cleanup.js';
try{clearRetiredCollections(localStorage);}catch{}
import {createClaim200UI} from './claim200-ui.js';
import {claim200Protocol} from './claim200-protocol.js';
import {mountGlobalFish} from './global-fish.js';
import {startLocalization,getLocale,speciesLabel} from './i18n.js';
import {continuousProgress} from './continuous-client.js';
import {EvmClient,api,formatEther,receipt} from './evm-client.js';
const client=new EvmClient(),$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let page='home',revision=0,accountRevision=0,water=0,busy=false,assets=[],requestId=null,polling=false,lastStage='',guide=false,tier='all',query='',ready=false,heldLimit=24;
let revealing=null;const revealed=new Set();
function unrevealed(f){return !revealed.has(key()+':'+f.id)&&((revealing&&revealing.scope===key()&&String(f.id)===revealing.tokenId)||(requestId&&String(f.requestId)===String(requestId)));}
const pageHost=document.createElement('section');pageHost.id='module-page';pageHost.hidden=true;$('.phone').insertBefore(pageHost,$('.bottom-nav'));
const warning=document.createElement('div');warning.className='bnb-warning';warning.textContent='BNB 主网测试 · 正在读取配置';$('.phone').appendChild(warning);
document.body.insertAdjacentHTML('beforeend','<div class="portrait-notice">请竖屏体验钓鱼游戏</div>');
startLocalization();
Lake3D.mount($('#lake-webgl'),false,'月影湖');
const landingTip=document.createElement('div');landingTip.className='landing-tip';landingTip.textContent='点击水面选落点 · 拖动鱼竿轻晃 · 拖动空白处环视';$('.game').appendChild(landingTip);$('#lake-webgl').addEventListener('landingchange',()=>{landingTip.textContent='落点已选定 · 点击抛竿核对费用';});
const close=()=>{progressHost.inert=false;$('#modal').hidden=true;$('#modal').replaceChildren();$('.game').inert=false;$('.bottom-nav').inert=false;$('#wait-pill').inert=false;pageHost.inert=false;$('#lake-webgl').dataset.renderPaused='false';};
function sheet(html){close();progressHost.inert=true;$('#modal').innerHTML=`<section class="sheet" role="dialog" aria-modal="true"><button class="sheet-close" aria-label="关闭">×</button><div class="sheet-content">${html}</div></section>`;$('#modal').hidden=false;$('.game').inert=true;$('.bottom-nav').inert=true;$('#wait-pill').inert=true;pageHost.inert=true;$('#lake-webgl').dataset.renderPaused='true';$('.sheet-close').onclick=close;}
function error(e){if(e.revert?.name==='ProgressRequired'||e.shortMessage?.includes('ProgressRequired'))return '鱼获正在确认，暂不能改变垂钓资格。请稍后重试并核对钱包中的交易状态。';return e.code===4001||e.code==='ACTION_REJECTED'?'你已取消钱包操作，未继续提交。':e.shortMessage||e.message||String(e);}
function notice(e){sheet(`<h2>操作提示</h2><p class="bnb-error">${esc(error(e))}</p>`);}
let dockExpanded=false,progressModel=null;
const progressHost=document.createElement('section');progressHost.id='fishing-progress';progressHost.hidden=true;progressHost.setAttribute('aria-label','链上垂钓进度');$('.phone').appendChild(progressHost);
function setProgress(model){progressModel=model;progressHost.hidden=false;progressHost.dataset.tone=model.tone||'waiting';if(!progressHost.firstElementChild){progressHost.innerHTML='<div class="progress-heading"><span class="progress-dot"></span><strong></strong><small></small></div><p role="status"></p><div class="progress-actions"><button id="progress-details">全部垂钓记录 ↗</button></div>';$('#progress-details').onclick=()=>roundEntries();}progressHost.querySelector('strong').textContent=model.title;progressHost.querySelector('small').textContent=model.meta||'';const message=progressHost.querySelector('p');if(message.textContent!==model.detail)message.textContent=model.detail;if(client.continuous&&!$('#progress-withdraw')){const b=document.createElement('button');b.id='progress-withdraw';b.textContent='收起这支鱼竿';b.onclick=()=>withdrawRod(requestId);progressHost.querySelector('.progress-actions').appendChild(b);}if($('#progress-withdraw'))$('#progress-withdraw').hidden=!requestId||model.tone==='success'||model.tone==='complete';}
function syncDock(){$('#cast').disabled=busy||!!revealing;$('.phone').classList.remove('dock-waiting');$('#wait-pill').hidden=true;if((busy||requestId)&&!progressModel)setProgress({title:'正在读取垂钓进度',detail:'抛竿、鱼篓和记录按钮将保持可用。'});}
$('#wait-pill').onclick=()=>roundEntries();
function status(title,hint,label){$('#status-title').textContent=title;$('#status-hint').textContent=hint;$('#cast-title').textContent=label==='连接钱包'?'抛竿':label;$('#cast-sub').textContent='BNB CHAIN · ERC-721';$('#cast').disabled=busy||!!revealing;if(busy)setProgress({title,detail:hint});syncDock();}
function showPage(name,title,sub,html){revision++;close();page=name;warning.hidden=name!=='home';pageHost.dataset.page=name;pageHost.hidden=name==='home';pageHost.classList.remove('collapsed');$('.game').style.visibility='visible';$('#lake-webgl').dataset.renderPaused='false';document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='home')return;pageHost.innerHTML=`<header class="module-header"><div><span class="eyebrow">主网测试 · ${sub}</span><h1>${title}</h1></div><button class="module-account">${client.address?client.address.slice(0,6)+'…'+client.address.slice(-4):'连接钱包'}</button><button class="panel-fold" aria-label="收起面板" aria-expanded="true">−</button><button class="panel-close" aria-label="关闭面板">×</button></header><div class="module-scroll">${html}</div>`;$('.module-account').onclick=walletDialog;$('.panel-close').onclick=()=>showPage('home');$('.panel-fold').onclick=()=>{const folded=pageHost.classList.toggle('collapsed');$('.panel-fold').textContent=folded?'+':'−';$('.panel-fold').setAttribute('aria-expanded',String(!folded));$('.panel-fold').setAttribute('aria-label',folded?'展开面板':'收起面板');};}
function dateLabel(value,dateOnly=false){const d=new Date(value);return Number.isFinite(d.getTime())?`<time datetime="${d.toISOString()}" data-date-style="${dateOnly?'date':'datetime'}">${dateOnly?d.toLocaleDateString(getLocale()):d.toLocaleString(getLocale())}</time>`:'—';}
function key(){return `Bnbfish-bnb:${client.config.chainId}:${client.config.contract}:${client.address}`;}
function records(){try{return JSON.parse(localStorage.getItem(key()+':tx')||'[]');}catch{return [];}}
function saveTx(tx,kind,extra={},k=key()+':tx'){let list=[];try{list=JSON.parse(localStorage.getItem(k)||'[]');}catch{}try{localStorage.setItem(k,JSON.stringify([{hash:tx.hash,kind,at:Date.now(),...extra},...list.filter(x=>x.hash!==tx.hash)].slice(0,100)));}catch{}return k;}
function markTx(k,hash,state){try{const rows=JSON.parse(localStorage.getItem(k)||'[]');localStorage.setItem(k,JSON.stringify(rows.map(x=>x.hash===hash?{...x,state}:x)));}catch{}}
async function connect(provider){try{await client.connect(provider?.request?provider:window.ethereum);accountRevision++;$('#account span').textContent=client.address.slice(0,6)+'…'+client.address.slice(-4);assets=[];requestId=null;lastStage='';close();if(client.contract){progressModel=null;progressHost.hidden=true;const pending=await client.pendingTicket();requestId=pending===0n?null:pending.toString();if(!requestId){try{requestId=localStorage.getItem(key()+':request');}catch{}}}if(page==='records')openRecords();else if(page==='bag')openBag();poll();if(client._listened!==client.injected){client._listened?.removeListener?.('accountsChanged',invalidate);client._listened?.removeListener?.('chainChanged',invalidate);client.injected.on?.('accountsChanged',invalidate);client.injected.on?.('chainChanged',invalidate);client._listened=client.injected;}}catch(e){notice(e);}}
const walletProviders=new Map();
window.addEventListener('eip6963:announceProvider',e=>{if(e.detail?.provider?.request)walletProviders.set(e.detail.info.uuid,e.detail);});
window.dispatchEvent(new Event('eip6963:requestProvider'));
function walletDialog(){
 const addr=client.address;
 sheet(`<div class="wallet-dialog"><span class="eyebrow">YOUR WALLET · YOUR CATCH</span><div class="evm-emblem">◇</div><h2>${addr?'钱包已连接':'连接你的钱包'}</h2><p>在 BNB Chain，收藏每一次相遇。</p><div class="network-pill"><i></i>${esc(client.config?.name||'BNB Smart Chain')} · ${client.config?.chainId||56}</div>${addr?`<div class="connected-address">${esc(addr)}</div><button class="sheet-action" id="view-wallet">打开 鱼获记录 ↗</button><button class="disconnect-wallet" id="disconnect-wallet">断开本页连接</button>`:`<div id="wallet-options"></div><p class="wallet-disclosure">连接用于读取公开地址。签名与交易均在钱包中确认，本站不接收助记词或私钥。</p>`}</div>`);
 if(addr){$('#view-wallet').onclick=openRecords;$('#disconnect-wallet').onclick=invalidate;return;}
 const entries=[...walletProviders.values()];
 $('#wallet-options').innerHTML=entries.length?entries.map((w,i)=>`<button class="provider-option" data-provider="${i}"><span class="provider-mark">◇</span><span><b>${esc(w.info.name)}</b><small>浏览器钱包 · EVM</small></span><span>↗</span></button>`).join(''):`<button class="provider-option" id="browser-wallet"><span class="provider-mark">◇</span><span><b>浏览器钱包</b><small>${window.ethereum?'已检测到 EVM 钱包':'请安装 MetaMask 等 EVM 扩展'}</small></span><span>↗</span></button>`;
 document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>connect(entries[Number(b.dataset.provider)].provider));
 $('#browser-wallet')?.addEventListener('click',()=>connect());
}
function invalidate(){revealing=null;progressModel=null;progressHost.hidden=true;$('#account span').textContent='连接钱包';accountRevision++;revision++;client.address=null;client.signer=null;assets=[];requestId=null;busy=false;lastStage='';close();showPage('home');Lake3D.feedback('reset');status('钱包已变化','请重新连接账户后继续','连接钱包');}
async function refreshStatus(){try{const d=await api('/api/status'+(client.scope||''));ready=d.ready;document.querySelector('[data-network=rpc]').dataset.state=d.height?'ok':'error';document.querySelector('[data-network=contract]').dataset.state=d.ready?'ok':'error';warning.textContent=client.config.local?'本地开发网络 · 模拟随机数 · 不是真实 BNB':!client.config.contract?'BNB 主网测试 · 合约尚未部署':!d.ready?'BNB 主网测试 · '+(d.reason||'服务未就绪'):'BNB 主网公开测试 · 非正式运营';if(!requestId&&!busy)status(d.ready?'水域已就绪':'等待链上配置',d.ready?'抛竿后等待可验证随机结果':d.reason||'服务未就绪',client.address?'抛竿':'连接钱包');}catch{ready=false;warning.textContent='BNB 服务暂不可用，图鉴仍可浏览';}}
$('#account').onclick=walletDialog;
$('#water-picker').onclick=()=>{if(busy||(!client.continuous&&!client.claim200&&requestId))return;sheet(`<h2>切换水域</h2><div class="water-grid">${FishGuide.waters.map(w=>`<button class="water-tile" data-water="${w.id}"><b>${w.name}</b><small>前往垂钓 →</small></button>`).join('')}</div>`);document.querySelectorAll('[data-water]').forEach(b=>b.onclick=()=>{water=Number(b.dataset.water);const name=FishGuide.waters[water].name;Lake3D.mount($('#lake-webgl'),false,name);$('.location h2').textContent=name;$('.location>span').textContent=Waters[name].label;$('.location p').textContent=Waters[name].mood;close();});};
$('#bait-picker').onclick=()=>client.claim200?sheet('<h2>清水饵</h2><p>每杆协议费 0.00001 BNB，网络 Gas 另计。鱼获锁定后可随时领取，领取只支付网络 Gas。</p>'):sheet('<span class="eyebrow">LIGHT TACKLE</span><h2>清水饵</h2><p>仅需网络 Gas。提交前估算，最终金额以钱包确认为准。</p><p class="module-note">点击湖面选择落点，拖动鱼竿轻晃。抛竿交易消耗网络 Gas，鱼获结果以当前合约规则为准。</p>');
function protocolDialog(){return sheet(claim200Protocol());}
$('#dock-more').onclick=()=>{sheet('<h2>垂钓手记</h2><div class="detail-rows"><div><span>当前装备</span><b>碳素鱼竿 · 清水饵</b></div></div><p class="module-note">点击水面选择落点，拖动鱼竿轻晃，拖动空白湖面环视。费用以当前合约规则与钱包确认内容为准。</p><button class="sheet-action" id="round-entries">垂钓记录与鱼获进度</button><button class="sheet-action" id="demo-settings">查看协议说明 ↗</button><a class="sheet-action copyright-link" href="/copyright/" target="_blank" rel="noopener">版权与使用说明 ↗</a><p class="module-note">© 2026 bnbfish开源项目库 · 仅供娱乐与收藏</p>');$('#demo-settings').onclick=protocolDialog;$('#round-entries').onclick=()=>roundEntries();};
document.querySelectorAll('[data-network]').forEach(b=>b.onclick=()=>sheet(`<h2>BNB Chain 连接</h2><p>${esc(client.config?.name||'读取中')}</p><p>合约：${esc(client.config?.contract||'尚未部署')}</p><p class="module-note">${ready?'链上服务已就绪':'真实交易尚未就绪；没有生成模拟 NFT。'}</p>`));
$('#cast').onclick=async()=>{if(busy)return;if(!client.address)return walletDialog();if(!ready)return notice(Error('BNB 合约未就绪，暂未开放垂钓'));if(records().some(r=>r.kind==='钓鱼费用'&&!r.state)){await recoverCast();if(requestId)return poll();if(records().some(r=>r.kind==='钓鱼费用'&&!r.state))return notice(Error('上次抛竿交易尚未确认，可在钱包扩展查询；确认后会自动恢复，不会重复提交。'));}busy=true;status('正在估算网络费用','直接调用 BNB 合约，无需登录签名','准备中');const token=accountRevision;
 try{const q=await client.prepareCast(water,()=>status('正在确认已有鱼讯','系统会等待资格可变更后，再请你确认抛竿','请稍候'));if(token!==accountRevision)return;sheet(`<h2>确认抛竿</h2><p class="module-note">主网公开测试 · 非正式运营。此操作发送真实 BNB 主网交易，并消耗真实 Gas。</p><div class="detail-rows"><div><span>预估 Gas</span><b>${formatEther(q.gasCost)} BNB</b></div><div><span>预估合计</span><b>${formatEther(q.gasCost+(q.fee||0n))} BNB</b></div>${q.fee?'<div><span>协议费（每杆）</span><b>0.00001 BNB</b></div>':''}</div><p class="module-note">${client.claim200?'每 200 区块一批，每地址每批一次，最多 50 份鱼获。获得鱼获后由你自行领取；不领取永久保留。每杆协议费 0.00001 BNB，网络 Gas 另计，无鱼获也不退回协议费。':client.continuous?'每次抛竿独立持续垂钓，获得鱼获或主动收竿后结束。首次资格等待10～19个区块，随后每10个区块判定鱼讯；未获鱼会继续等待，无需重复付费抛竿。只有网络Gas，最终金额以钱包为准。':'每次抛竿增加一张机会，可重复参与。20% 机会先判为空竿，其余参与本周期的随机鱼获判定，每周期最多产生 1 枚 NFT；没有鱼获也消耗 Gas。最终网络费以钱包为准。'}</p><button class="sheet-action" id="approve-cast">前往钱包确认</button>`);
 $('#approve-cast').onclick=async()=>{if(busy)return;busy=true;dockExpanded=false;close();if(page!=='home'){pageHost.classList.add('collapsed');$('.panel-fold').textContent='+';$('.panel-fold').setAttribute('aria-expanded','false');$('.panel-fold').setAttribute('aria-label','展开面板');}Lake3D.cast();status('抛竿入水','等待钱包确认并提交链上','提交中');try{const storageKey=key()+':tx';const tx=await client.sendCast(q,()=>status('正在确认已有鱼讯','确认完成后将打开钱包，无需额外结算操作','请稍候'));const k=saveTx(tx,'钓鱼费用',{},storageKey);status('鱼饵已入水','交易已发送，等待入块','守漂中');const r=await receipt(tx);markTx(k,tx.hash,r.status===1?'已入块':'失败');if(token!==accountRevision)return;const log=r.logs.map(l=>{try{return client.contract.interface.parseLog(l);}catch{return null;}}).find(l=>l?.name==='CastRequested');if(!log)throw Error('交易未包含抛竿事件');requestId=client.castTicketId(log);localStorage.setItem(key()+':request',requestId);lastStage='';}catch(e){if(token===accountRevision){Lake3D.feedback('reset');notice(e);}}finally{if(token===accountRevision){busy=false;syncDock();if(!requestId)status('等待下一次抛竿','查看鱼获记录以确认交易状态','抛竿');poll();}}};
 }catch(e){if(token===accountRevision)notice(e);}finally{if(token===accountRevision){busy=false;$('#cast').disabled=false;syncDock();}}
};
async function poll(manual=false){return client.claim200?claimUI.poll():pollContinuous(manual);}
function card(s,f){if(f&&unrevealed(f))return '<div class="nft-card"><div class="nft-image" style="display:grid;place-items:center">≈</div><div class="nft-card-copy"><b>鱼儿正在出水…</b><small>上鱼后揭晓收藏卡</small></div></div>'; const t=FishGuide.tiers.find(t=>t.id===s.rarity);return `<button class="nft-card" data-tier="${t.id}" style="--rarity:${t.color}" ${f?`data-token="${esc(f.id)}"`:`data-species="${s.id}"`}><div class="nft-image">${NftFrame.ornament(t.id)}${FishArt({name:s.name,collectible:true})}<span class="nft-status">${f?'NFT':'图鉴'}</span></div>${NftFrame.band(t.id)}<div class="nft-card-copy"><b class="rarity-label">${esc(s.name)}</b><small>${t.name}</small><span>${f?f.lengthMm/10:s.lengthMinMm/10} cm${f?' · '+dateLabel(f.caughtAt*1000,true):''}</span></div></button>`;}
function wireCards(){document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>detail(FishGuide.species.find(s=>s.id===Number(b.dataset.species))));document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{const f=assets.find(a=>a.id===b.dataset.token);detail(FishGuide.species.find(s=>s.id===f.speciesId),f);});}
function detail(s,f){if(f&&unrevealed(f))return;sheet(`${NftFrame.detail({name:s.name,rarity:s.rarity,guide:!f,length:(f?f.lengthMm/10:s.lengthMinMm/10+'–'+s.lengthMaxMm/10)+' cm',weight:f?f.massGrams/1000+' kg':null,group:s.group||'水生物种',footer:f?'BNB · NFT #'+f.id:'Bnbfish · SPECIES ARCHIVE'})}<p class="nft-value-note">NFT 没有任何经济价值属性，仅作为收藏娱乐。</p><p class="module-note">${f?'链上 ERC-721 · 获得于 '+dateLabel(f.caughtAt*1000):'物种图鉴，不代表你已持有 NFT。'+(!s.enabled?'该物种仅收录展示，不产出。':'')}</p>${f?'<button class="sheet-action" id="transfer-nft">转账这枚 NFT</button>':''}`);$('#transfer-nft')?.addEventListener('click',()=>transfer(f));}
async function openBag(mode=guide){guide=mode;showPage('bag','我的鱼篓','BNB · COLLECTION',`<div class="collection-notice"><span>仅供收藏娱乐</span><div><b>NFT 没有任何经济价值属性</b><p>鱼获仅用于游戏收藏与娱乐，不代表投资、收益或兑换权益。</p></div></div><div class="bag-summary"><div><small>链上 NFT</small><b id="bag-count">—</b></div><div><small>图鉴物种</small><b>100</b></div><button id="bag-refresh">↻ 刷新</button></div><div class="bag-tabs"><button id="held-tab" class="${!guide?'selected':''}">我的鱼获</button><button id="guide-tab" class="${guide?'selected':''}">水生图鉴</button></div><div id="bag-content"></div>`);$('#held-tab').onclick=()=>openBag(false);$('#guide-tab').onclick=()=>openBag(true);$('#bag-refresh').onclick=()=>openBag();const token=revision;
 if(guide){$('#bag-content').innerHTML=`<label class="guide-search"><input id="guide-search" placeholder="搜索鱼、蟹、虾、贝" value="${esc(query)}"></label><div class="segment-filters">${[{id:'all',name:'全部'},...FishGuide.tiers].map(t=>`<button data-filter="${t.id}" class="${tier===t.id?'selected':''}">${t.name}</button>`).join('')}</div><div class="nft-grid" id="guide-grid"></div>`;$('#guide-search').oninput=e=>{query=e.target.value;renderGuide();};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{tier=b.dataset.filter;openBag(true);});renderGuide();$('#bag-count').textContent=client.address?assets.length:'—';return;}
 $('#bag-content').innerHTML='<p class="module-note">最新鱼获在前 · 按链上获得时间排序</p><div id="held-grid" class="nft-grid"></div><p id="bag-state" class="bnb-busy">正在读取 ERC-721 持仓…</p>';
 if(!client.address){$('#bag-state').innerHTML='<span class="empty-illustration">⌁</span><b>把湖里的故事，收进鱼篓</b><span>连接钱包查看你的鱼获，或先翻阅 100 种水生图鉴。</span><button id="empty-guide">翻开水生图鉴 ↗</button>';$('#empty-guide').onclick=()=>openBag(true);return;}if(!client.contract){$('#bag-state').textContent='合约尚未部署，当前没有可读取的 BNB 鱼获。';return;}
 try{const list=await client.holdings();if(token!==revision)return;assets=list;$('#bag-count').textContent=list.length;$('#bag-state').textContent=list.length?'':'这个地址还没有鱼获 NFT。';renderHeld();}catch(e){if(token===revision)$('#bag-state').textContent=error(e);}}
function renderGuide(){const list=FishGuide.species.filter(s=>(tier==='all'||s.rarity===tier)&&[s.name,s.scientificName,...s.aliases,...['en','ru','ja'].map(lang=>speciesLabel(s,lang))].filter(Boolean).some(n=>n.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())));$('#guide-grid').innerHTML=list.map(s=>card(s)).join('');wireCards();}
function renderHeld(){const list=assets.slice(0,heldLimit);$('#held-grid').innerHTML=list.map(f=>card(FishGuide.species.find(s=>s.id===f.speciesId),f)).join('');$('#load-more')?.remove();if(assets.length>heldLimit){$('#bag-state').insertAdjacentHTML('afterend','<button class="sheet-action" id="load-more">查看更多鱼获</button>');$('#load-more').onclick=()=>{heldLimit+=24;renderHeld();};}wireCards();}
let historyRows=[],historyBefore=null,historyScope='',historyBusy=false;
function historyKey(){return key()+':nft-history';}
function openRecords(transfers=false){if(client.claim200&&transfers!==true)return claimUI.showRecords();
 showPage('records','鱼获记录','BNBFISH · FISHING JOURNAL',`<div class="collection-notice"><span>仅供收藏娱乐</span><div><b>NFT 没有任何经济价值属性</b><p>鱼获仅用于游戏收藏与娱乐，不代表投资、收益或兑换权益。</p></div></div><div class="records-toolbar"><div><h2>湖畔手记</h2><p>收获与流转，按时间珍藏</p></div><button id="refresh-history">同步记录</button></div><div class="history-filters"><button data-history="all" class="selected">全部</button><button data-history="mint">获得鱼获</button><button data-history="in">转入</button><button data-history="out">转出</button></div><div id="nft-history"></div><p id="history-state" class="module-note"></p><button id="history-more" class="history-more" hidden>加载更早记录</button>`);
 const scope=client.address?historyKey():'';
 if(scope!==historyScope){historyScope=scope;historyBefore=null;try{historyRows=scope?JSON.parse(localStorage.getItem(scope)||'[]'):[];}catch{historyRows=[];}}
 let selected='all';
 const render=()=>{const rows=historyRows.filter(r=>selected==='all'||r.kind===selected);$('#nft-history').innerHTML=rows.length?rows.map(r=>{const s=FishGuide.species.find(s=>s.id===r.speciesId);if(r.kind==='mint'&&unrevealed(r))return `<article class="nft-event"><div class="event-art">≈</div><div class="event-title"><b>鱼儿正在出水…</b><span>链上已确认 · 上鱼动作结束后揭晓鱼种</span></div></article>`;return `<article class="nft-event"><div class="event-art">${s?FishArt({name:s.name,collectible:true}):'◇'}</div><div class="event-title"><b>${esc(s?.name||'鱼获')} <small>#${esc(r.id)}</small></b><span>${r.kind==='mint'?'获得鱼获':r.kind==='in'?'NFT 转入':'NFT 转出'} · ${dateLabel(r.at*1000)}</span><code title="${esc(r.from)}">来自 ${esc(r.kind==='mint'?'链上生成':r.from)}</code><code title="${esc(r.to)}">至 ${esc(r.to)}</code>${s?`<small>${esc(FishGuide.tiers.find(t=>t.id===s.rarity)?.name)} · ${r.lengthMm/10} cm · ${r.massGrams/1000} kg</small>`:''}</div><div class="event-proof"><span>区块 #${esc(r.block)}</span>${client.config.explorer?`<a target="_blank" rel="noopener noreferrer" href="${esc(client.config.explorer)}/tx/${encodeURIComponent(r.hash)}">查看链上记录 ↗</a>`:`<code>${r.hash.slice(0,12)}…</code>`}</div></article>`;}).join(''):'<div class="history-empty"><span>◇</span><h3>下一页，等你写下</h3><p>连接钱包，查看每次收获和鱼获流转的足迹。</p></div>';const pending=client.address?records().filter(r=>r.kind==='NFT 转出'&&!historyRows.some(h=>h.hash===r.hash)):[];if(pending.length)$('#nft-history').insertAdjacentHTML('afterbegin',pending.map(r=>`<div class="pending-nft">NFT 转出 · ${esc(r.state||'已提交，等待确认')}（本机提交记录） <code>${esc(r.hash.slice(0,16))}…</code></div>`).join(''));};
 document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{selected=b.dataset.history;document.querySelectorAll('[data-history]').forEach(x=>x.classList.toggle('selected',x===b));render();});
 render();const token=revision;
 const load=async(older=false)=>{if(historyBusy)return;if(!client.address)return walletDialog();if(!client.contract){$('#history-state').textContent='合约尚未部署，暂时没有链上 鱼获记录。';return;}historyBusy=true;$('#refresh-history').disabled=true;$('#history-more').disabled=true;$('#history-state').textContent='正在读取链上 NFT 事件…';try{const pendingRows=records().filter(r=>r.kind==='NFT 转出'&&!r.state);await Promise.all(pendingRows.map(async r=>{const receipt=await client.reader.getTransactionReceipt(r.hash);if(receipt)markTx(key()+':tx',r.hash,receipt.status===1?'已入块':'失败');}));let result=await client.nftActivity(older?historyBefore:null,range=>{if(token===revision)$('#history-state').textContent=`正在查找历史鱼获 · 已查至区块 ${range.fromBlock}…`;});while(!result.rows.length&&result.more&&token===revision){const next=await client.nftActivity(result.fromBlock-1,range=>{if(token===revision)$('#history-state').textContent=`正在查找历史鱼获 · 已查至区块 ${range.fromBlock}…`;});result={...next,toBlock:result.toBlock};}if(token!==revision)return;const map=new Map((older?historyRows:historyRows.filter(r=>r.block<result.fromBlock)).map(r=>[r.hash+':'+r.index,r]));result.rows.forEach(r=>map.set(r.hash+':'+r.index,r));historyRows=[...map.values()].sort((a,b)=>b.block-a.block||b.index-a.index);historyBefore=result.fromBlock-1;try{localStorage.setItem(scope,JSON.stringify(historyRows));}catch{}render();$('#history-state').textContent=`已核验区块 ${result.fromBlock}–${result.toBlock}。${result.more?'可继续加载更早的链上记录。':'已到达合约部署区块。'}`;$('#history-more').hidden=!result.more;}catch(e){if(token===revision)$('#history-state').textContent='链上读取未完成：'+error(e);}finally{historyBusy=false;if(token===revision){$('#refresh-history').disabled=false;$('#history-more').disabled=false;}}};
 $('#refresh-history').onclick=()=>load();$('#history-more').onclick=()=>load(true);
 if(!client.address)$('#history-state').textContent='请通过右上角连接 EVM 钱包。';else load();
}
function transfer(f){transactionForm('NFT 转账',`<p>转出 NFT #${f.id} · ${esc(FishGuide.species.find(s=>s.id===f.speciesId).name)}</p>`,to=>client.prepareTransfer(f.id,to),q=>client.transfer(q),'NFT 转出');}
function transactionForm(title,extra,prepare,send,kind){sheet(`<h2>${title}</h2>${extra}<label>收款地址<input id="recipient" placeholder="0x…" autocomplete="off"></label><div id="quote"></div><button id="prepare" class="sheet-action">核对并估算 Gas</button><p id="tx-state" class="bnb-busy"></p>`);let q=null,completed=false;const token=accountRevision,b=$('#prepare'),state=$('#tx-state');b.onclick=async()=>{b.disabled=true;const inputs=[...$('#modal').querySelectorAll('input')];inputs.forEach(i=>i.disabled=true);try{if(!q){q=await prepare($('#recipient').value.trim());if(token!==accountRevision||!b.isConnected)return;$('#quote').innerHTML=`<p class="module-note">收款：${esc(q.to)}<br>${q.value?'金额：'+formatEther(q.value)+' BNB<br>':''}预估 Gas：${formatEther(q.gasCost)} BNB</p>`;b.textContent='前往钱包签名确认';state.textContent='请核对，尚未提交交易。';}else{state.textContent='等待钱包确认…';const storageKey=key()+':tx';const tx=await send(q),k=saveTx(tx,kind,{},storageKey);b.textContent='查看 鱼获记录';b.onclick=openRecords;if(b.isConnected)state.textContent='已提交，可关闭窗口，在 鱼获记录中查看。';await receipt(tx);markTx(k,tx.hash,'已入块');if(token===accountRevision&&b.isConnected){completed=true;b.textContent='已完成';b.disabled=true;state.textContent='交易已入块。';return;}}}catch(e){if(b.isConnected)state.textContent=error(e);if(!q)inputs.forEach(i=>i.disabled=false);}finally{if(b.isConnected&&!completed)b.disabled=false;}};}
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>({home:()=>showPage('home'),bag:()=>openBag(false),records:openRecords}[b.dataset.nav])());
document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});
const globalFish=mountGlobalFish({getConfig:()=>client.config,isHidden:row=>unrevealed({id:row.tokenId,requestId:row.ticketId})});
const claimUI=createClaim200UI({client,$,esc,sheet,close,showPage,notice,error,receipt,saveTx,markTx,key,walletDialog,setProgress,syncDock,openTransfers:()=>openRecords(true),getAutomation:()=>api('/api/automation'),getRequest:()=>requestId,isBusy:()=>busy,setRevealing:(on,id)=>{revealing=on?{scope:key(),tokenId:'unclaimed-'+id}:null;syncDock();},clearRequest:()=>{requestId=null;try{localStorage.removeItem(key()+':request');}catch{}}});
window.addEventListener('bnbfish:claimed',e=>{if(e.detail.scope!==key())return;assets=[];globalFish.refresh();if(!$('#modal').hidden)return;if(page==='records')claimUI.showRecords('claimed',true);else if(page==='bag')openBag(true);});
try{await client.init();globalFish.refresh();warning.textContent=client.config.local?'本地开发网络 · 非 BNB 主网':client.config.contract?'BNB 主网测试 · 正在检查服务':'BNB 主网测试 · 合约尚未部署';$('.gear-description').textContent=client.claim200?'0.00001 BNB + Gas':'仅网络 Gas';await refreshStatus();}catch(e){warning.textContent='BNB 配置读取失败 · '+error(e);}
setInterval(()=>{if(!document.hidden){if(requestId)poll();else if(client.address){recoverCast();recoverActiveRod();}}},4000);setInterval(()=>{if(!document.hidden)refreshStatus();},30000);

let recovering=false;
async function recoverCast(){if(recovering||!client.address||!client.contract)return;const row=records().find(r=>r.kind==='钓鱼费用'&&!r.state);if(!row)return;recovering=true;const token=accountRevision,k=key()+':tx';try{const r=await client.reader.getTransactionReceipt(row.hash);if(!r||token!==accountRevision)return;markTx(k,row.hash,r.status===1?'已入块':'失败');if(r.status===1){const log=r.logs.map(l=>{try{return client.contract.interface.parseLog(l);}catch{return null;}}).find(l=>l?.name==='CastRequested');if(log){requestId=client.castTicketId(log);localStorage.setItem(key()+':request',requestId);lastStage='';}}}catch{}finally{recovering=false;}}

async function roundEntries(limit=20){if(client.claim200)return claimUI.showRecords();if(client.continuous)return continuousEntries(limit);
 if(!client.address)return walletDialog();if(!client.contract)return notice(Error('合约尚未部署'));
 sheet('<h2>垂钓记录</h2><p class="module-note">每次抛竿独立记录，后续自动确认鱼获。空竿也会消耗真实网络 Gas。</p><div id="round-state">读取链上记录…</div><div id="round-list"></div>');
 const host=$('#round-list'),state=$('#round-state'),rev=accountRevision;
 try{const count=Number(await client.contract.playerTicketCount(client.address)),first=Math.max(0,count-limit),rows=[];
 for(let end=count;end>first;end-=6){rows.push(...await Promise.all(Array.from({length:Math.min(6,end-first)},async(_,i)=>{const id=await client.contract.playerTicketAt(client.address,end-i-1),c=await client.contract.casts(id),rid=await client.contract.ticketRound(id);const eligible=Number(c.state)===3&&c.tokenId===0n?await client.contract.ticketEligible(id):null;return{id,c,rid,eligible};})));}
 if(rev!==accountRevision||!host.isConnected)return;
 host.innerHTML=rows.map(({id,c,rid,eligible})=>`<div class="detail-rows"><div><span>抛竿 #${id} · 水面周期 ${rid}</span><b>${Number(c.state)===3?(c.tokenId>0n?'获得 NFT #'+c.tokenId:eligible?'已确认 · 空竿':'已确认 · 空竿'):Number(c.state)===2?'鱼获确认中':'等待鱼讯'}</b></div></div>`).join('')||'<p>尚未抛竿。</p>';
 state.textContent='显示最近 '+rows.length+' 次 / 共 '+count+' 次抛竿 · 鱼获自动确认';
 if(count>limit){host.insertAdjacentHTML('beforeend','<button class="sheet-action" id="more-entries">查看更多垂钓记录</button>');$('#more-entries').onclick=()=>roundEntries(limit+20);}
 }catch(e){if(state.isConnected)state.textContent=error(e);}
}

async function pollContinuous(manual=false){
 if(polling||busy||!requestId||!client.contract||!client.address)return;
 polling=true;const rev=accountRevision,id=requestId;
 try{
  const s=await client.fishingState(id);if(rev!==accountRevision||requestId!==id)return;
  if(s.ticket.player.toLowerCase()!==client.address.toLowerCase())throw Error('垂钓记录不属于当前地址');
  const state=Number(s.ticket.state);
  if(state===1){
   let automation=null;try{automation=await api('/api/automation'+(client.scope||''));}catch{}
   if(rev!==accountRevision||requestId!==id)return;
   setProgress(continuousProgress({...s,id},automation));status('持续垂钓中','未获鱼会自动继续等待','追加抛竿');
   const bite=s.node.winner===BigInt(id)&&Number(s.node.state)===1;
   const stage=(bite?'bite:':'waiting:')+id;
   if(lastStage!==stage){lastStage=stage;await Lake3D.feedback(bite?'bite':'waiting');}
   return;
  }
  if(state!==2&&state!==3)throw Error('未找到有效垂钓记录');
  let data,sp;if(state===2){data=await client.contract.fish(s.ticket.tokenId);sp=FishGuide.species.find(x=>x.id===Number(data.speciesId));}
  if(rev!==accountRevision||requestId!==id)return;
  if(state===2)revealing={scope:key(),tokenId:String(s.ticket.tokenId)};syncDock();
  setProgress({title:state===2?'鱼儿上钩了 · 正在牵引靠岸':'这支鱼竿已收起',detail:state===2?'链上已确认鱼获，出水后揭晓收藏卡。':'收竿已在链上确认。',meta:'垂钓 #'+id,tone:'complete'});
  if(lastStage!=='done:'+id){lastStage='done:'+id;await Lake3D.feedback(state===2?'catch':'reset',{name:sp?.name,size:Math.max(.65,Math.min(1.65,Number(data?.lengthMm||700)/700))});
   if(rev!==accountRevision||requestId!==id)return;
   if(state===2)revealed.add(key()+':'+s.ticket.tokenId);revealing=null;
   if(state===2&&page==='home')sheet(`${NftFrame.detail({name:sp?.name||'鱼获',rarity:sp?.rarity||'common',length:Number(data.lengthMm)/10+' cm',weight:Number(data.massGrams)/1000+' kg',footer:'BNB · NFT #'+s.ticket.tokenId})}<p class="module-note">${esc(FishingQuips.pick('catch'))}</p>`);
  }
  requestId=null;try{localStorage.removeItem(key()+':request');}catch{}
  setProgress({title:state===2?'鱼获已到账 · '+sp?.name:'这支鱼竿已收起',detail:state===2?'NFT #'+s.ticket.tokenId+' · 可在鱼篓查看收藏卡。':'收竿已在链上确认。',tone:state===2?'success':'complete'});
  if(page==='records')openRecords();if(page==='bag')openBag();status('鱼讯已确认','可在垂钓记录查看每支鱼竿','再次抛竿');
  const next=await client.pendingTicket();if(rev===accountRevision&&next!==0n){requestId=next.toString();localStorage.setItem(key()+':request',requestId);}
 }catch(e){if(rev===accountRevision){setProgress({title:'链上读取暂未完成',detail:error(e)+'。将自动重试，不会把读取失败当作空竿。',tone:'attention'});if(manual)notice(e);}}
 finally{if(rev===accountRevision)revealing=null;polling=false;syncDock();}
}
async function continuousEntries(limit=20){
 if(!client.address)return walletDialog();if(!client.contract)return notice(Error('合约尚未部署'));
 sheet('<h2>我的垂钓记录</h2><p class="module-note">鱼获、鱼种与每支鱼竿的链上状态</p><div id="round-state">正在核验链上记录…</div><div id="round-list"></div>');$('#modal .sheet').classList.add('compact-entries');
 const host=$('#round-list'),state=$('#round-state'),rev=accountRevision;
 try{let before=null,rows=[],count=0;do{const result=await client.fishingEntries(Math.min(100,limit-rows.length),before);rows.push(...result.rows);count=result.count;before=result.more?result.before:0;}while(before>0&&rows.length<limit);
  if(rev!==accountRevision||!host.isConnected)return;
  const fishMap=new Map();
  for(let i=0;i<rows.length;i+=4){await Promise.all(rows.slice(i,i+4).filter(r=>Number(r.ticket.state)===2).map(async r=>{try{fishMap.set(String(r.id),await client.contract.fish(r.ticket.tokenId));}catch{}}));}
  if(rev!==accountRevision||!host.isConnected)return;
  host.innerHTML=rows.map(({id,ticket:t})=>{
   const fish=fishMap.get(String(id)),hidden=Number(t.state)===2&&unrevealed({id:String(t.tokenId),requestId:String(id)}),sp=!hidden&&fish?FishGuide.species.find(s=>s.id===Number(fish.speciesId)):null,tier=FishGuide.tiers.find(t=>t.id===sp?.rarity);
   const label=sp?speciesLabel(sp):Number(t.state)===1?'持续垂钓':Number(t.state)===3?'已收竿':hidden?'鱼种待揭晓':'鱼获资料暂未读取';
   return `<article class="rod-record" style="--rod-color:${esc(tier?.color||'#96adb8')}"><div class="rod-art">${sp?`<img src="/nft-images/${sp.id}.png" alt="${esc(speciesLabel(sp))}" loading="lazy" width="900" height="1200">`:'<span>≈</span>'}</div><div class="rod-copy"><b>${esc(label)}</b><small>${sp?esc(tier?.name||sp.rarity)+' · ':''}鱼竿 #${id}${Number(t.state)===2?' · NFT #'+t.tokenId:''}</small><small>${esc(FishGuide.waters[Number(t.water)]?.name||'水域')} · ${dateLabel(Number(t.castAt)*1000)}</small></div>${Number(t.state)===1?`<div class="rod-actions"><button data-watch="${id}">查看鱼讯</button><button data-withdraw="${id}">收竿</button></div>`:`<span class="rod-badge">${Number(t.state)===2?'已获鱼':'已结束'}</span>`}</article>`;
  }).join('')||'<p>还没有垂钓记录，去湖边抛下第一竿。</p>';
  state.textContent='最近 '+rows.length+' 条 / 共 '+count+' 条 · 状态来自链上';
  host.querySelectorAll('[data-watch]').forEach(b=>b.onclick=()=>{requestId=b.dataset.watch;localStorage.setItem(key()+':request',requestId);lastStage='';close();poll();});
  host.querySelectorAll('[data-withdraw]').forEach(b=>b.onclick=()=>withdrawRod(b.dataset.withdraw));
  if(before>0){const button=document.createElement('button');button.className='sheet-action';button.textContent='查看更多垂钓记录';button.onclick=()=>continuousEntries(limit+20);host.appendChild(button);}
 }catch(e){if(rev===accountRevision&&state.isConnected)state.textContent=error(e);}
}
async function withdrawRod(id){
 if(!id||busy)return;busy=true;const rev=accountRevision;
 const waiting=()=>status('当前鱼讯正在确认','确认完成后会继续收竿操作','请稍候');
 try{const q=await client.prepareWithdraw(id,waiting);if(rev!==accountRevision)return;
  sheet(`<h2>收起鱼竿 #${esc(id)}</h2><p class="module-note">仅结束这支鱼竿的后续垂钓资格，已经获得的NFT和其他鱼竿不受影响。</p><div class="detail-rows"><div><span>预估网络 Gas</span><b>${formatEther(q.gasCost)} BNB</b></div></div><button class="sheet-action" id="confirm-withdraw">前往钱包确认收竿</button>`);
  $('#confirm-withdraw').onclick=async()=>{if(busy)return;busy=true;close();try{const tx=await client.withdraw(q,waiting);const k=saveTx(tx,'收竿',{ticketId:id});const r=await receipt(tx);markTx(k,tx.hash,r.status===1?'已入块':'失败');if(rev!==accountRevision)return;if(r.status!==1)throw Error('收竿交易未成功');requestId=id;lastStage='';}catch(e){if(rev===accountRevision)notice(e);}finally{if(rev===accountRevision){busy=false;poll();syncDock();}}};
 }catch(e){if(rev===accountRevision)notice(e);}finally{if(rev===accountRevision){busy=false;syncDock();}}
}

let activeRecovering=false,lastActiveRecovery=0;
async function recoverActiveRod(){
 if(activeRecovering||busy||polling||requestId||!client.address||!client.contract||Date.now()-lastActiveRecovery<15000)return;
 activeRecovering=true;lastActiveRecovery=Date.now();const rev=accountRevision;
 try{const next=await client.pendingTicket();if(rev===accountRevision&&!requestId&&next!==0n){requestId=String(next);localStorage.setItem(key()+':request',requestId);lastStage='';poll();}}catch{}finally{activeRecovering=false;}
}
