import {translate as t,getLocale,speciesLabel} from './i18n.js';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function mountGlobalFish({getConfig,isHidden=()=>false}){
 const root=document.createElement('aside');root.id='global-fish';root.dataset.noTranslate='';root.dataset.open='false';root.innerHTML='<button class="global-fish-toggle" aria-expanded="false" aria-controls="global-fish-content"><span class="global-live-dot"></span><span class="global-fish-heading"></span><span class="global-fish-chevron">⌃</span></button><p class="global-fish-ticker" aria-live="polite"></p><div class="global-fish-totals"></div><section id="global-fish-content" hidden><p class="global-fish-note"></p><div class="global-fish-tabs"></div><div class="global-fish-body"></div><footer class="global-fish-footer"></footer></section>';
 document.querySelector('.game').appendChild(root);let snapshot=null,failed=false,loading=false,tab='recent',signature='',lastToken=null,timer;
 const button=root.querySelector('button'),content=root.querySelector('section');button.onclick=()=>{const open=content.hidden;content.hidden=!open;root.dataset.open=String(open);button.setAttribute('aria-expanded',String(open));render();};
 const number=n=>new Intl.NumberFormat(getLocale()).format(n),species=id=>window.FishGuide.species.find(s=>s.id===id),label=id=>{const s=species(id);return s?speciesLabel(s):'#'+id;};
 function render(){
  const stale=failed||snapshot?.stale;root.dataset.stale=String(!!stale);button.setAttribute('aria-label',t(content.hidden?'展开全网鱼讯':'收起全网鱼讯'));root.querySelector('.global-fish-heading').textContent=t('全网鱼讯');
  const row=snapshot?.latest[0],ticker=root.querySelector('.global-fish-ticker');
  const announcement=row?(isHidden(row)?t('你的鱼儿正在出水，稍后揭晓鱼种。'):`${row.player.slice(0,6)}…${row.player.slice(-4)} ${t('钓上了')} ${label(row.speciesId)}`):t(snapshot?'暂无已领取鱼获，已锁定鱼获计入总数。':failed?'鱼讯暂不可用，稍后自动重试。':'正在同步全网鱼讯…');if(ticker.textContent!==announcement)ticker.textContent=announcement;
  const newToken=row?.tokenId;if(lastToken&&newToken!==lastToken){root.classList.remove('fresh-catch');void root.offsetWidth;root.classList.add('fresh-catch');}lastToken=newToken;
  root.querySelector('.global-fish-totals').innerHTML=`<span>${escape(t('鱼获总数（含未领取）'))} <b>${snapshot?number(snapshot.total):'—'}</b></span><span>${escape(t('未领取'))} <b>${snapshot?number(snapshot.unclaimed):'—'}</b></span><span>${escape(t('已领取'))} <b>${snapshot?number(snapshot.claimed):'—'}</b></span><span>${escape(t('已出现种类'))} <b>${snapshot?number(snapshot.speciesCount):'—'}</b> / 100</span>${stale?`<em>${escape(t('更新延迟'))}</em>`:''}`;
  if(content.hidden)return;
  root.querySelector('.global-fish-note').textContent=t('总数包含已锁定未领取与已领取鱼获；转账不重复计数。');
  const tabs=root.querySelector('.global-fish-tabs');if(!tabs.children.length){for(const id of ['recent','species']){const b=document.createElement('button');b.dataset.tab=id;b.onclick=()=>{tab=id;signature='';render();};tabs.appendChild(b);}}
  for(const b of tabs.children){b.textContent=t(b.dataset.tab==='recent'?'最近领取':'鱼种统计');b.setAttribute('aria-pressed',String(tab===b.dataset.tab));}
  const hidden=snapshot?.latest.map(row=>isHidden(row));const nextSignature=JSON.stringify([snapshot?.latest,snapshot?.species,getLocale(),tab,hidden,failed,snapshot?.stale]);const body=root.querySelector('.global-fish-body');
  if(signature!==nextSignature){signature=nextSignature;const scroll=body.scrollTop;body.innerHTML=!snapshot?`<p class="global-fish-empty">${escape(t(failed?'鱼讯暂不可用，稍后自动重试。':'正在同步全网鱼讯…'))}</p>`:tab==='recent'?snapshot.latest.map(row=>{const pending=isHidden(row),name=pending?t('鱼种待揭晓'):label(row.speciesId),s=species(row.speciesId),color=FishGuide.tiers.find(tier=>tier.id===s?.rarity)?.color||'#718b98';return `<article class="global-catch-row"><span class="global-catch-mark" style="--fish-color:${escape(color)}">${pending?'≈':`<img src="/nft-images/${row.speciesId}.png" alt="${escape(name)}" loading="lazy" width="900" height="1200">`}</span><div><b>${escape(name)}</b><small title="${escape(row.player)}">${escape(row.player.slice(0,6)+'…'+row.player.slice(-4))} · ${escape(new Date(row.caughtAt*1000).toLocaleString(getLocale(),{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}))}</small></div>${pending?`<span>${escape(t('出水中'))}</span>`:`<a target="_blank" rel="noopener noreferrer" href="${escape(getConfig().explorer+'/token/'+getConfig().contract+'?a='+row.tokenId)}" aria-label="${escape(t('查看链上记录'))} #${row.tokenId}">#${row.tokenId} ↗</a>`}</article>`;}).join('')||`<p>${escape(t('暂无已领取鱼获，已锁定鱼获计入总数。'))}</p>`:snapshot.latest.some(isHidden)?`<p class="global-fish-empty">${escape(t('你的鱼儿正在出水，稍后揭晓鱼种。'))}</p>`:snapshot.species.map(row=>`<div class="global-species-row"><img src="/nft-images/${row.speciesId}.png" alt="" loading="lazy" width="900" height="1200"><span>${escape(label(row.speciesId))}</span><b>${number(row.count)}</b></div>`).join('')||`<p>${escape(t('尚无鱼种记录'))}</p>`;body.scrollTop=scroll;}
  root.querySelector('.global-fish-footer').textContent=snapshot?`${t(stale?'更新延迟':'已同步')} · ${t('区块')} ${number(snapshot.blockNumber)} · ${t('约每 12 秒更新')}`:t('鱼讯暂不可用，稍后自动重试。');
 }
 function valid(data,config){return data.chainId===config.chainId&&data.contract?.toLowerCase()===config.contract?.toLowerCase()&&Number.isSafeInteger(data.total)&&data.total>=0&&data.total<=2000000&&Number.isSafeInteger(data.claimed)&&Number.isSafeInteger(data.unclaimed)&&data.claimed>=0&&data.unclaimed>=0&&data.claimed+data.unclaimed===data.total&&Number.isSafeInteger(data.blockNumber)&&Array.isArray(data.latest)&&data.latest.length<=12&&Array.isArray(data.species)&&data.species.length<=100&&data.species.every(r=>species(r.speciesId)&&Number.isSafeInteger(r.count)&&r.count>0)&&new Set(data.species.map(r=>r.speciesId)).size===data.species.length&&data.species.reduce((n,r)=>n+r.count,0)===data.total&&data.speciesCount===data.species.length&&data.latest.every(r=>/^\d{1,7}$/.test(r.tokenId)&&Number(r.tokenId)<=data.total&&/^\d+$/.test(r.ticketId)&&/^0x[0-9a-f]{40}$/i.test(r.player)&&species(r.speciesId)&&Number.isSafeInteger(r.caughtAt)&&r.caughtAt>0);}
 async function refresh(){if(loading||document.hidden)return;const config=getConfig();if(!config?.contract)return;if(config.archived){root.hidden=true;return;}loading=true;const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),22000);try{const response=await fetch('/api/global-catches',{signal:controller.signal,cache:'no-store'});if(!response.ok)throw Error('Unavailable');const data=await response.json();if(!valid(data,config))throw Error('Invalid snapshot');snapshot=data;failed=false;}catch{failed=true;}finally{clearTimeout(timeout);loading=false;render();}}
 window.addEventListener('bnbfish:language',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});render();refresh();timer=setInterval(refresh,12000);let hiddenState='';const revealTimer=setInterval(()=>{if(!document.hidden&&snapshot){const next=JSON.stringify(snapshot.latest.map(isHidden));if(next!==hiddenState){hiddenState=next;render();}}},2000);
 return {refresh,dispose(){clearInterval(timer);clearInterval(revealTimer);root.remove();window.removeEventListener('bnbfish:language',render);}};
}
