/* Real lake recording; event sounds are excerpts used as water foley. */
window.LakeAudio=(()=>{
 let ctx,buffer,loop,master,enabled=true,loading=false;const voices=new Set();
 try{enabled=localStorage.getItem('Bnbfish-bnb-sound-enabled')!=='false';}catch{}
 const button=document.createElement('button');button.type='button';button.className='lake-sound-toggle';button.textContent='声景 · 关闭';button.setAttribute('aria-pressed','false');button.title='上钩提示音与湖水声 · 点击开关';
 button.style.cssText='position:absolute;right:18px;top:205px;z-index:12;border:1px solid #dcebf477;border-radius:18px;padding:7px 12px;background:#183345bb;color:#edf8ff;font:12px system-ui;cursor:pointer';
 function sync(){button.textContent=enabled?'音效 · 开启':'音效 · 关闭';button.setAttribute('aria-pressed',String(enabled));}
 function stop(){window.CatchChime?.stop();loop?.stop();loop=null;voices.forEach(s=>{try{s.stop();}catch{}});voices.clear();}
 function ambient(){if(!enabled||document.hidden||!buffer||loop)return;loop=ctx.createBufferSource();loop.buffer=buffer;loop.loop=true;const gain=ctx.createGain();gain.gain.value=.72;loop.connect(gain).connect(master);loop.start();}
 function prepare(){ctx ||= new AudioContext();if(!master){master=ctx.createGain();master.gain.value=.92;const limiter=ctx.createDynamicsCompressor();limiter.threshold.value=-10;limiter.knee.value=8;limiter.ratio.value=6;limiter.attack.value=.003;limiter.release.value=.18;master.connect(limiter).connect(ctx.destination);}return ctx.resume();}
 async function start(){if(!enabled||loading||document.hidden)return;loading=true;try{await prepare();if(!buffer){buffer=await ctx.decodeAudioData(await (await fetch('assets/audio/lake-volta.ogg')).arrayBuffer());let peak=0;for(let c=0;c<buffer.numberOfChannels;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++)peak=Math.max(peak,Math.abs(d[i]));}const gain=Math.min(5,.85/Math.max(.01,peak));for(let c=0;c<buffer.numberOfChannels;c++){const d=buffer.getChannelData(c);for(let i=0;i<d.length;i++)d[i]*=gain;}}ambient();}catch{}finally{loading=false;sync();}}
 function toggle(){enabled=!enabled;try{localStorage.setItem('Bnbfish-bnb-sound-enabled',String(enabled));}catch{}if(enabled){if(master)master.gain.value=.92;start();}else{stop();if(master)master.gain.value=0;}sync();}
 // User gesture unlocks audio before asynchronous chain results arrive.
 document.addEventListener('pointerdown',()=>{if(enabled&&(!ctx||ctx.state!=='running'||!buffer))start();},{passive:true});
 document.addEventListener('keydown',()=>{if(enabled&&(!ctx||ctx.state!=='running'))start();},{passive:true});
 sync();
 button.addEventListener('click',toggle);document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();ctx?.suspend();}else if(enabled){start();}});window.addEventListener('pagehide',stop);
 return {notify(kind){if(!enabled||document.hidden||!ctx||!master)return;window.CatchChime?.play(ctx,master,kind);},mount(host){const parent=host.parentElement;if(getComputedStyle(parent).position==='static')parent.style.position='relative';parent.appendChild(button);if(!parent.querySelector('.sound-credit')){const credit=document.createElement('a');credit.className='sound-credit';credit.href='assets/audio/README.md';credit.target='_blank';credit.textContent='音源许可';credit.style.cssText='position:absolute;right:28px;top:244px;z-index:12;font:10px system-ui;color:#e0edf3;text-shadow:0 1px 3px #123';parent.appendChild(credit);}},event(kind){if(!enabled||!buffer||document.hidden||voices.size>=4)return;const s=ctx.createBufferSource(),g=ctx.createGain();s.buffer=buffer;s.playbackRate.value=kind==='escape'?1.15:kind==='bite'?1.4:.95;g.gain.setValueAtTime(0,ctx.currentTime);g.gain.linearRampToValueAtTime(kind==='bite'?1.15:1.55,ctx.currentTime+.03);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.8);s.connect(g).connect(master);voices.add(s);s.onended=()=>{voices.delete(s);g.disconnect();};s.start(0,Math.min(buffer.duration-1,kind==='bite'?2:5),.85);}};
})();
